const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const serviceSchema = new mongoose.Schema({
  _id: { type: String, default: uuidv4 },
  name: { 
    type: String, 
    required: true,
    enum: [
      'Plumbing',
      'Electrical Work',
      'Carpentry',
      'Painting',
      'Cleaning',
      'Gardening',
      'Masonry',
      'Roofing',
      'Tiling',
      'Welding',
      'HVAC',
      'Generator Repairer', // <-- added
      'Pest Control',
      'Locksmith',
      'Mechanic',
      'Auto Detailing',
      'Electronics Repair',
      'Furniture Making',
      'Interior Design',
      'Exterior Design',
      'Pool Maintenance',
      'Landscape Design',
      'Home Renovation',
      'Appliance Repair',
      'Glass Installation/Repair',
      'Flooring',
      'Plastering',
      'Gutter Cleaning/Installation',
      'Concrete Work',
      'Drywall Installation',
      'Sewing/Tailoring',
      'Fashion Design',
      'Jewelry Making',
      'Catering Services',
      'Baking/Pastry',
      'Barber/Hairdresser',
      'Beauty Therapy',
      'Massage Therapy',
      'Tattoo Artist',
      'Makeup Artist',
      'Photography',
      'Videography',
      'Music Lessons',
      'Dance Instructor',
      'Fitness Trainer',
      'Yoga Instructor',
      'Dog Walking/Pet Care',
      'Pet Grooming',
      'Carpet Cleaning',
      'Window Cleaning',
      'Chimney Sweeping',
      'Solar Panel Installation',
      'IT Services',
      'Web Development',
      'Graphic Design',
      '3D Printing',
      'Other'
    ] 
  },
  description: { type: String },
  price: { type: Number, required: true },
  duration: { type: Number, default: 60 },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Service', serviceSchema);